"""
Catalogue d'équipements adiabatiques basé sur les fiches techniques Seeley International.
Extrait depuis les PDFs fournis : CW-80, CW-H, EA120, CW3, EXS220, TBSI580
"""

import sqlite3
import json
from app.core.database import get_db

CATALOGUE_EQUIPEMENTS = [
    # ============================================================
    # FAMILLE CW-80 — Climatisation adiabatique industrielle large
    # ============================================================
    {
        "reference": "CW-80-IEC-STD",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-80",
        "type_equipement": "adiabatique_iec",
        "description": "Refroidisseur adiabatique indirect CW-80 IEC ventilateurs standard",
        "debit_air_nominal": 23800,   # m³/h @ 400Pa (config C)
        "debit_air_min": 20900,
        "debit_air_max": 26600,
        "puissance_electrique": 12.5, # kW
        "puissance_refroidissement_standalone": 64,  # kW
        "puissance_refroidissement_precooling": 148,
        "cop_standalone": 5,
        "cop_precooling": 12,
        "temperature_soufflage": 19.5,  # °C (IEC)
        "temperature_soufflage_min": 19.1,
        "temperature_soufflage_max": 20.0,
        "pression_statique_max": 600,  # Pa
        "tension": "380-440V / 3~ / 50-60Hz",
        "courant_nominal": 26,  # A
        "debit_eau": 250,  # L/hr consommation
        "pression_eau_min": 85,  # kPa
        "pression_eau_max": 800,
        "reservoir_litres": 180,
        "nb_echangeurs_indirect": 16,
        "nb_echangeurs_direct": 0,
        "dimension_longueur": 3980,  # mm
        "dimension_largeur": 2550,
        "dimension_hauteur": 3515,
        "poids_operation": 2700,  # kg
        "temp_air_entree_max": 50,  # °C
        "surface_couverte_indicative": 1200,  # m² (estimation projet)
        "nb_unites_par_1000m2": 0.83,
        "prix_indicatif_eur": 35000,
        "certifications": "EN 378, ASHRAE 15",
        "type_ventilateur": "Centrifuge 2x560mm",
        "vitesse_max_rpm": 1750,
        "controle": "ECM Variable Speed 0-10V",
        "doc_reference": "ES E222-B AU2306"
    },
    {
        "reference": "CW-80-IEC-HIGH",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-80",
        "type_equipement": "adiabatique_iec",
        "description": "Refroidisseur adiabatique indirect CW-80 IEC ventilateurs haute capacité",
        "debit_air_nominal": 25900,
        "debit_air_min": 19100,
        "debit_air_max": 30600,
        "puissance_electrique": 14.2,
        "puissance_refroidissement_standalone": 68,
        "puissance_refroidissement_precooling": 159,
        "cop_standalone": 5,
        "cop_precooling": 11,
        "temperature_soufflage": 19.7,
        "temperature_soufflage_min": 18.7,
        "temperature_soufflage_max": 20.4,
        "pression_statique_max": 820,
        "tension": "380-440V / 3~ / 50-60Hz",
        "courant_nominal": 29,
        "debit_eau": 265,
        "pression_eau_min": 85,
        "pression_eau_max": 800,
        "reservoir_litres": 180,
        "nb_echangeurs_indirect": 16,
        "nb_echangeurs_direct": 0,
        "dimension_longueur": 3980,
        "dimension_largeur": 2550,
        "dimension_hauteur": 3515,
        "poids_operation": 2700,
        "temp_air_entree_max": 50,
        "surface_couverte_indicative": 1400,
        "nb_unites_par_1000m2": 0.71,
        "prix_indicatif_eur": 38000,
        "certifications": "EN 378, ASHRAE 15",
        "type_ventilateur": "Centrifuge 2x560mm",
        "vitesse_max_rpm": 1750,
        "controle": "ECM Variable Speed 0-10V",
        "doc_reference": "ES E222-B AU2306"
    },
    {
        "reference": "CW-80-SC-STD",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-80",
        "type_equipement": "adiabatique_supercool",
        "description": "CW-80 Supercool ventilateurs standard — refroidissement indirect+direct",
        "debit_air_nominal": 22700,
        "debit_air_min": 19800,
        "debit_air_max": 25600,
        "puissance_electrique": 12.5,
        "puissance_refroidissement_standalone": 88,
        "puissance_refroidissement_precooling": 167,
        "cop_standalone": 7,
        "cop_precooling": 13,
        "temperature_soufflage": 16.1,  # Supercool
        "temperature_soufflage_min": 15.9,
        "temperature_soufflage_max": 16.3,
        "pression_statique_max": 580,
        "tension": "380-440V / 3~ / 50-60Hz",
        "courant_nominal": 27,
        "debit_eau": 275,
        "pression_eau_min": 85,
        "pression_eau_max": 800,
        "reservoir_litres": 180,
        "nb_echangeurs_indirect": 16,
        "nb_echangeurs_direct": 2,  # Chillcel pads
        "dimension_longueur": 3980,
        "dimension_largeur": 2550,
        "dimension_hauteur": 3515,
        "poids_operation": 2850,
        "temp_air_entree_max": 50,
        "surface_couverte_indicative": 1100,
        "nb_unites_par_1000m2": 0.91,
        "prix_indicatif_eur": 40000,
        "certifications": "EN 378, ASHRAE 15",
        "type_ventilateur": "Centrifuge 2x560mm",
        "vitesse_max_rpm": 1750,
        "controle": "ECM Variable Speed 0-10V",
        "doc_reference": "ES E222-B AU2306"
    },
    {
        "reference": "CW-80-SC-HIGH",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-80",
        "type_equipement": "adiabatique_supercool",
        "description": "CW-80 Supercool ventilateurs haute capacité — plus haute capacité de refroidissement",
        "debit_air_nominal": 23400,
        "debit_air_min": 18000,
        "debit_air_max": 29500,
        "puissance_electrique": 14.2,
        "puissance_refroidissement_standalone": 91,
        "puissance_refroidissement_precooling": 173,
        "cop_standalone": 6,
        "cop_precooling": 12,
        "temperature_soufflage": 16.0,
        "temperature_soufflage_min": 15.5,
        "temperature_soufflage_max": 16.4,
        "pression_statique_max": 825,
        "tension": "380-440V / 3~ / 50-60Hz",
        "courant_nominal": 30,
        "debit_eau": 295,
        "pression_eau_min": 85,
        "pression_eau_max": 800,
        "reservoir_litres": 180,
        "nb_echangeurs_indirect": 16,
        "nb_echangeurs_direct": 2,
        "dimension_longueur": 3980,
        "dimension_largeur": 2550,
        "dimension_hauteur": 3515,
        "poids_operation": 2850,
        "temp_air_entree_max": 50,
        "surface_couverte_indicative": 1300,
        "nb_unites_par_1000m2": 0.77,
        "prix_indicatif_eur": 43000,
        "certifications": "EN 378, ASHRAE 15",
        "type_ventilateur": "Centrifuge 2x560mm",
        "vitesse_max_rpm": 1750,
        "controle": "ECM Variable Speed 0-10V",
        "doc_reference": "ES E222-B AU2306"
    },

    # ============================================================
    # FAMILLE CW-H — Taille intermédiaire / commerciale
    # ============================================================
    {
        "reference": "CW-H10",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-H",
        "type_equipement": "adiabatique_iec",
        "description": "CW-H10 refroidisseur adiabatique compact — petit commercial",
        "debit_air_nominal": 2880,   # m³/h @ 180Pa
        "debit_air_min": 2000,
        "debit_air_max": 3500,
        "puissance_electrique": 1.5,
        "puissance_refroidissement_standalone": 8,
        "puissance_refroidissement_precooling": 18,
        "cop_standalone": 5,
        "cop_precooling": 12,
        "temperature_soufflage": 19.5,
        "temperature_soufflage_min": 18.5,
        "temperature_soufflage_max": 21.5,
        "pression_statique_max": 180,
        "tension": "380-415V / 3N~ / 50Hz",
        "courant_nominal": 4.9,
        "debit_eau": 44,  # L/hr
        "pression_eau_min": 100,
        "pression_eau_max": 800,
        "reservoir_litres": 45,
        "nb_echangeurs_indirect": 2,
        "nb_echangeurs_direct": 0,
        "dimension_longueur": 2330,
        "dimension_largeur": 1230,
        "dimension_hauteur": 1325,
        "poids_operation": 255,
        "temp_air_entree_max": 55,
        "surface_couverte_indicative": 120,
        "nb_unites_par_1000m2": 8.3,
        "prix_indicatif_eur": 8500,
        "certifications": "IEC 60335, AS/NZS 60335",
        "type_ventilateur": "Centrifuge 1x560mm",
        "vitesse_max_rpm": 1285,
        "controle": "ECM Variable Speed PWM",
        "doc_reference": "ES E061-Q AU2206"
    },
    {
        "reference": "CW-H15",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-H",
        "type_equipement": "adiabatique_iec",
        "description": "CW-H15 refroidisseur adiabatique moyen — commercial standard",
        "debit_air_nominal": 3960,
        "debit_air_min": 2800,
        "debit_air_max": 5000,
        "puissance_electrique": 1.8,
        "puissance_refroidissement_standalone": 11,
        "puissance_refroidissement_precooling": 25,
        "cop_standalone": 6,
        "cop_precooling": 14,
        "temperature_soufflage": 19.5,
        "temperature_soufflage_min": 18.5,
        "temperature_soufflage_max": 21.5,
        "pression_statique_max": 180,
        "tension": "380-415V / 3N~ / 50Hz",
        "courant_nominal": 4.9,
        "debit_eau": 56,
        "pression_eau_min": 100,
        "pression_eau_max": 800,
        "reservoir_litres": 65,
        "nb_echangeurs_indirect": 3,
        "nb_echangeurs_direct": 0,
        "dimension_longueur": 2290,
        "dimension_largeur": 1825,
        "dimension_hauteur": 1285,
        "poids_operation": 330,
        "temp_air_entree_max": 55,
        "surface_couverte_indicative": 200,
        "nb_unites_par_1000m2": 5.0,
        "prix_indicatif_eur": 11000,
        "certifications": "IEC 60335, AS/NZS 60335",
        "type_ventilateur": "Centrifuge 1x560mm",
        "vitesse_max_rpm": 1350,
        "controle": "ECM Variable Speed PWM",
        "doc_reference": "ES E061-Q AU2206"
    },
    {
        "reference": "CW-H15S",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-H",
        "type_equipement": "adiabatique_supercool",
        "description": "CW-H15S Supercool — efficacité énergétique maximale",
        "debit_air_nominal": 3960,
        "debit_air_min": 2800,
        "debit_air_max": 5000,
        "puissance_electrique": 1.8,
        "puissance_refroidissement_standalone": 16,
        "puissance_refroidissement_precooling": 29,
        "cop_standalone": 8.5,
        "cop_precooling": 16,
        "temperature_soufflage": 15.8,  # Supercool
        "temperature_soufflage_min": 15.5,
        "temperature_soufflage_max": 17.5,
        "pression_statique_max": 120,
        "tension": "380-415V / 3N~ / 50Hz",
        "courant_nominal": 4.9,
        "debit_eau": 60,
        "pression_eau_min": 100,
        "pression_eau_max": 800,
        "reservoir_litres": 65,
        "nb_echangeurs_indirect": 3,
        "nb_echangeurs_direct": 3,
        "dimension_longueur": 2290,
        "dimension_largeur": 1825,
        "dimension_hauteur": 1285,
        "poids_operation": 345,
        "temp_air_entree_max": 55,
        "surface_couverte_indicative": 200,
        "nb_unites_par_1000m2": 5.0,
        "prix_indicatif_eur": 13500,
        "certifications": "IEC 60335, AS/NZS 60335",
        "type_ventilateur": "Centrifuge 1x560mm",
        "vitesse_max_rpm": 1350,
        "controle": "ECM Variable Speed PWM",
        "doc_reference": "ES E061-Q AU2206"
    },
    {
        "reference": "CW-H15S-PLUS",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW-H",
        "type_equipement": "adiabatique_supercool",
        "description": "CW-H15S Plus — capacité de refroidissement maximale",
        "debit_air_nominal": 5760,
        "debit_air_min": 4000,
        "debit_air_max": 6700,
        "puissance_electrique": 2.1,
        "puissance_refroidissement_standalone": 20,
        "puissance_refroidissement_precooling": 40,
        "cop_standalone": 9.5,
        "cop_precooling": 19,
        "temperature_soufflage": 17.4,
        "temperature_soufflage_min": 16.5,
        "temperature_soufflage_max": 19.0,
        "pression_statique_max": 80,
        "tension": "380-415V / 3N~ / 50Hz",
        "courant_nominal": 4.9,
        "debit_eau": 72,
        "pression_eau_min": 100,
        "pression_eau_max": 800,
        "reservoir_litres": 65,
        "nb_echangeurs_indirect": 3,
        "nb_echangeurs_direct": 3,
        "dimension_longueur": 2290,
        "dimension_largeur": 1825,
        "dimension_hauteur": 1285,
        "poids_operation": 345,
        "temp_air_entree_max": 55,
        "surface_couverte_indicative": 280,
        "nb_unites_par_1000m2": 3.6,
        "prix_indicatif_eur": 15000,
        "certifications": "IEC 60335, AS/NZS 60335",
        "type_ventilateur": "Centrifuge 1x560mm",
        "vitesse_max_rpm": 1460,
        "controle": "ECM Variable Speed PWM",
        "doc_reference": "ES E061-Q AU2206"
    },

    # ============================================================
    # FAMILLE EA120 — Refroidisseur évaporatif direct résidentiel/petit commercial
    # ============================================================
    {
        "reference": "EA120D",
        "fabricant": "Seeley International",
        "marque": "Breezair",
        "gamme": "EA120",
        "type_equipement": "evaporatif_direct",
        "description": "EA120D refroidisseur évaporatif direct — soufflage vers le bas",
        "debit_air_nominal": 7270,   # m³/h @ 80Pa
        "debit_air_min": 4320,
        "debit_air_max": 8170,
        "puissance_electrique": 1.147,
        "puissance_refroidissement_standalone": 11.3,
        "puissance_refroidissement_precooling": 0,
        "cop_standalone": 6.97,  # EER
        "cop_precooling": 0,
        "temperature_soufflage": 0,  # Direct = pas IEC
        "temperature_soufflage_min": 0,
        "temperature_soufflage_max": 0,
        "pression_statique_max": 200,
        "tension": "220-240V / 1~ / 50Hz",
        "courant_nominal": 6.0,
        "debit_eau": 0,  # Pas de gestion chloration
        "pression_eau_min": 0,
        "pression_eau_max": 0,
        "reservoir_litres": 25,
        "nb_echangeurs_indirect": 0,
        "nb_echangeurs_direct": 4,  # pads Aspen
        "dimension_longueur": 1060,
        "dimension_largeur": 945,
        "dimension_hauteur": 870,
        "poids_operation": 95,
        "temp_air_entree_max": 45,
        "surface_couverte_indicative": 50,
        "nb_unites_par_1000m2": 20,
        "prix_indicatif_eur": 1800,
        "certifications": "AS 2913-2000, ASHRAE 143",
        "type_ventilateur": "Centrifuge double aspiration",
        "vitesse_max_rpm": 1400,
        "controle": "PSC Variable Speed",
        "doc_reference": "ES E013-F EU 2105"
    },
    {
        "reference": "EA120S",
        "fabricant": "Seeley International",
        "marque": "Breezair",
        "gamme": "EA120",
        "type_equipement": "evaporatif_direct",
        "description": "EA120S refroidisseur évaporatif direct — soufflage latéral",
        "debit_air_nominal": 6190,
        "debit_air_min": 2990,
        "debit_air_max": 7130,
        "puissance_electrique": 1.147,
        "puissance_refroidissement_standalone": 9.3,
        "puissance_refroidissement_precooling": 0,
        "cop_standalone": 6.97,
        "cop_precooling": 0,
        "temperature_soufflage": 0,
        "temperature_soufflage_min": 0,
        "temperature_soufflage_max": 0,
        "pression_statique_max": 200,
        "tension": "220-240V / 1~ / 50Hz",
        "courant_nominal": 6.0,
        "debit_eau": 0,
        "pression_eau_min": 0,
        "pression_eau_max": 0,
        "reservoir_litres": 38,
        "nb_echangeurs_indirect": 0,
        "nb_echangeurs_direct": 3,
        "dimension_longueur": 1060,
        "dimension_largeur": 945,
        "dimension_hauteur": 870,
        "poids_operation": 106,
        "temp_air_entree_max": 45,
        "surface_couverte_indicative": 40,
        "nb_unites_par_1000m2": 25,
        "prix_indicatif_eur": 1700,
        "certifications": "AS 2913-2000, ASHRAE 143",
        "type_ventilateur": "Centrifuge double aspiration",
        "vitesse_max_rpm": 1400,
        "controle": "PSC Variable Speed",
        "doc_reference": "ES E013-F EU 2105"
    },

    # ============================================================
    # CW3 — Résidentiel / petit commercial indirect+direct
    # ============================================================
    {
        "reference": "CW3",
        "fabricant": "Seeley International",
        "marque": "Climate Wizard",
        "gamme": "CW3",
        "type_equipement": "adiabatique_supercool",
        "description": "CW3 refroidisseur indirect/direct résidentiel — Micro-Core",
        "debit_air_nominal": 4680,  # m³/h @ 150Pa
        "debit_air_min": 3830,
        "debit_air_max": 5710,
        "puissance_electrique": 1.75,
        "puissance_refroidissement_standalone": 13,
        "puissance_refroidissement_precooling": 29,
        "cop_standalone": 7.5,
        "cop_precooling": 17,
        "temperature_soufflage": 19.3,
        "temperature_soufflage_min": 18.7,
        "temperature_soufflage_max": 20.2,
        "pression_statique_max": 250,
        "tension": "220-240V / 1~",
        "courant_nominal": 7.0,
        "debit_eau": 60,
        "pression_eau_min": 100,
        "pression_eau_max": 800,
        "reservoir_litres": 30,
        "nb_echangeurs_indirect": 8,
        "nb_echangeurs_direct": 8,
        "dimension_longueur": 1160,
        "dimension_largeur": 1160,
        "dimension_hauteur": 1020,
        "poids_operation": 210,
        "temp_air_entree_max": 50,
        "surface_couverte_indicative": 200,
        "nb_unites_par_1000m2": 5.0,
        "prix_indicatif_eur": 9500,
        "certifications": "IEC 60335, AS 2913-2000, ASHRAE 143",
        "type_ventilateur": "Axial 400mm + Centrifuge 380mm",
        "vitesse_max_rpm": 2400,
        "controle": "ECM Variable Speed PWM",
        "doc_reference": "ES E125-H AU2203"
    },

    # ============================================================
    # EXS220 — Evaporatif direct haute performance / Supercool
    # ============================================================
    {
        "reference": "EXS220",
        "fabricant": "Seeley International",
        "marque": "Breezair Supercool",
        "gamme": "EXS",
        "type_equipement": "evaporatif_direct",
        "description": "EXS220 Supercool — refroidisseur direct haute performance Chillcel",
        "debit_air_nominal": 9140,  # m³/h @ 80Pa
        "debit_air_min": 6160,
        "debit_air_max": 9790,
        "puissance_electrique": 1.86,
        "puissance_refroidissement_standalone": 15.1,
        "puissance_refroidissement_precooling": 0,
        "cop_standalone": 8.12,  # EER
        "cop_precooling": 0,
        "temperature_soufflage": 0,
        "temperature_soufflage_min": 0,
        "temperature_soufflage_max": 0,
        "pression_statique_max": 280,
        "tension": "220-240V / 1~ / 50Hz",
        "courant_nominal": 9.0,
        "debit_eau": 0,
        "pression_eau_min": 0,
        "pression_eau_max": 0,
        "reservoir_litres": 11,
        "nb_echangeurs_indirect": 0,
        "nb_echangeurs_direct": 4,  # Chillcel pads
        "dimension_longueur": 1160,
        "dimension_largeur": 1160,
        "dimension_hauteur": 860,
        "poids_operation": 94,
        "temp_air_entree_max": 45,
        "surface_couverte_indicative": 70,
        "nb_unites_par_1000m2": 14.3,
        "prix_indicatif_eur": 3500,
        "certifications": "AS 2913-2000, ASHRAE 143",
        "type_ventilateur": "Centrifuge 460mm",
        "vitesse_max_rpm": 680,
        "controle": "ECM Direct Drive Variable Speed",
        "doc_reference": "ES E122-B EU 2010"
    },

    # ============================================================
    # TBSI580 — Evaporatif direct Superstealth
    # ============================================================
    {
        "reference": "TBSI580",
        "fabricant": "Seeley International",
        "marque": "Breezair Supercool",
        "gamme": "TBSI",
        "type_equipement": "evaporatif_direct",
        "description": "TBSI580 Superstealth — haute efficacité évaporative directe",
        "debit_air_nominal": 10910,  # m³/h @ 80Pa
        "debit_air_min": 3600,
        "debit_air_max": 12240,
        "puissance_electrique": 1.5,
        "puissance_refroidissement_standalone": 18.4,
        "puissance_refroidissement_precooling": 0,
        "cop_standalone": 12.3,  # EER
        "cop_precooling": 0,
        "temperature_soufflage": 0,
        "temperature_soufflage_min": 0,
        "temperature_soufflage_max": 0,
        "pression_statique_max": 280,
        "tension": "200-240V / 1~ / 50Hz",
        "courant_nominal": 7.0,
        "debit_eau": 0,
        "pression_eau_min": 0,
        "pression_eau_max": 0,
        "reservoir_litres": 23,
        "nb_echangeurs_indirect": 0,
        "nb_echangeurs_direct": 4,
        "dimension_longueur": 1150,
        "dimension_largeur": 1150,
        "dimension_hauteur": 835,
        "poids_operation": 94,
        "temp_air_entree_max": 45,
        "surface_couverte_indicative": 80,
        "nb_unites_par_1000m2": 12.5,
        "prix_indicatif_eur": 2800,
        "certifications": "AS 2913-2000",
        "type_ventilateur": "Axial Superstealth 534mm",
        "vitesse_max_rpm": 1700,
        "controle": "Inverter Variable Speed",
        "doc_reference": "ES E102-C EU2004"
    },
]


def init_catalogue_equipements():
    """Initialise la table des équipements du catalogue."""
    conn = get_db()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS catalogue_equipements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            reference TEXT UNIQUE NOT NULL,
            fabricant TEXT,
            marque TEXT,
            gamme TEXT,
            type_equipement TEXT,
            description TEXT,
            debit_air_nominal REAL,
            debit_air_min REAL,
            debit_air_max REAL,
            puissance_electrique REAL,
            puissance_refroidissement_standalone REAL,
            puissance_refroidissement_precooling REAL,
            cop_standalone REAL,
            cop_precooling REAL,
            temperature_soufflage REAL,
            temperature_soufflage_min REAL,
            temperature_soufflage_max REAL,
            pression_statique_max REAL,
            tension TEXT,
            courant_nominal REAL,
            debit_eau REAL,
            pression_eau_min REAL,
            pression_eau_max REAL,
            reservoir_litres REAL,
            nb_echangeurs_indirect INTEGER,
            nb_echangeurs_direct INTEGER,
            dimension_longueur REAL,
            dimension_largeur REAL,
            dimension_hauteur REAL,
            poids_operation REAL,
            temp_air_entree_max REAL,
            surface_couverte_indicative REAL,
            nb_unites_par_1000m2 REAL,
            prix_indicatif_eur REAL,
            certifications TEXT,
            type_ventilateur TEXT,
            vitesse_max_rpm REAL,
            controle TEXT,
            doc_reference TEXT,
            en_stock INTEGER DEFAULT 0,
            quantite_stock INTEGER DEFAULT 0,
            notes_stock TEXT,
            date_ajout TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Table stock utilisateur (équipements personnels)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS stock_equipements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipement_id INTEGER,
            reference_catalogue TEXT,
            quantite INTEGER DEFAULT 1,
            etat TEXT DEFAULT 'neuf',
            localisation TEXT,
            date_acquisition TEXT,
            prix_achat REAL,
            notes TEXT,
            date_ajout TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (equipement_id) REFERENCES catalogue_equipements(id)
        )
    """)

    # Insérer le catalogue
    for eq in CATALOGUE_EQUIPEMENTS:
        try:
            cursor.execute("""
                INSERT OR IGNORE INTO catalogue_equipements
                (reference, fabricant, marque, gamme, type_equipement, description,
                 debit_air_nominal, debit_air_min, debit_air_max,
                 puissance_electrique, puissance_refroidissement_standalone,
                 puissance_refroidissement_precooling, cop_standalone, cop_precooling,
                 temperature_soufflage, temperature_soufflage_min, temperature_soufflage_max,
                 pression_statique_max, tension, courant_nominal,
                 debit_eau, pression_eau_min, pression_eau_max, reservoir_litres,
                 nb_echangeurs_indirect, nb_echangeurs_direct,
                 dimension_longueur, dimension_largeur, dimension_hauteur,
                 poids_operation, temp_air_entree_max,
                 surface_couverte_indicative, nb_unites_par_1000m2,
                 prix_indicatif_eur, certifications, type_ventilateur,
                 vitesse_max_rpm, controle, doc_reference)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """, tuple(eq.get(k) for k in [
                "reference", "fabricant", "marque", "gamme", "type_equipement", "description",
                "debit_air_nominal", "debit_air_min", "debit_air_max",
                "puissance_electrique", "puissance_refroidissement_standalone",
                "puissance_refroidissement_precooling", "cop_standalone", "cop_precooling",
                "temperature_soufflage", "temperature_soufflage_min", "temperature_soufflage_max",
                "pression_statique_max", "tension", "courant_nominal",
                "debit_eau", "pression_eau_min", "pression_eau_max", "reservoir_litres",
                "nb_echangeurs_indirect", "nb_echangeurs_direct",
                "dimension_longueur", "dimension_largeur", "dimension_hauteur",
                "poids_operation", "temp_air_entree_max",
                "surface_couverte_indicative", "nb_unites_par_1000m2",
                "prix_indicatif_eur", "certifications", "type_ventilateur",
                "vitesse_max_rpm", "controle", "doc_reference"
            ]))
        except Exception as e:
            print(f"Erreur insertion {eq['reference']}: {e}")

    conn.commit()
    conn.close()
    print(f"✅ Catalogue {len(CATALOGUE_EQUIPEMENTS)} équipements initialisé")
